[package]
name = "server"
version = "0.0.44"
edition = "2021"
build = "src/build.rs"

[dependencies]
iggy = { path = "../iggy" }
async-trait = "0.1.68"
axum = "0.6.20"
axum-server = { version = "0.5.1", features = ["tls-rustls", "tokio-rustls"] }
blake3 = "1.5.0"
bytes = "1.4.0"
figlet-rs = "0.1.5"
figment = { version = "0.10.8", features = ["json", "toml", "env"] }
flume = "0.11.0"
jsonwebtoken = "8.3.0"
thiserror = "1.0.40"
ring = "0.17.0"
rustls-pemfile = "1.0.3"
serde = { version = "1.0.159", features = ["derive", "rc"] }
serde_json = "1.0.95"
rmp-serde = "1.1.2"
serde_with = { version = "3.0.0", features = ["base64"] }
tokio = { version = "1.28.2", features = ["full"] }
tokio-rustls = "0.24.0"
tokio-native-tls = "0.3.1"
tower = { version = "0.4.13" }
tower-http = { version = "0.4.0", features = [
    "add-extension",
    "cors",
    "trace",
] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
clap = { version = "4.1.11", features = ["derive"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17", features = ["fmt"] }
tracing-appender = "0.2.2"
chrono = "0.4.30"
anyhow = "1.0.70"
tokio-graceful-shutdown = "0.13.0"
rcgen = "0.11.1"
quinn = "0.10.0"
rustls = { version = "0.21.1", features = ["dangerous_configuration", "quic"] }
aes-gcm = "0.10.3"
bcrypt = "0.15.0"
futures = "0.3.28"
sled = "0.34.7"
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "zerocopy"] }
sysinfo = "0.29.5"
strip-ansi-escapes = "0.2.0"
toml = "0.8.0"
prometheus-client = "0.21.2"
byte-unit = "4.0.19"
xxhash-rust = { version = "0.8.2", features = ["xxh32"] }
async_zip = { version = "0.0.15", features = ["full"] }
tokio-util = { version = "0.7.9", features = ["io"] }


[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.3"
libc = "0.2.147"
serial_test = "2.0.0"

[build-dependencies]
vergen = { version = "8.2.4", features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
] }

[[bin]]
name = "iggy-server"
path = "src/main.rs"
