[package]
name = "integration"
version = "0.0.1"
edition = "2021"

[dev-dependencies]
server = { path = "../server" }
iggy = { path = "../iggy", features = ["iggy-cmd"] }
assert_cmd = "2.0.12"
predicates = "3.0.3"
libc = "0.2.147"
serial_test = "2.0.0"
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "zerocopy"] }
tokio = { version = "1.28.2", features = ["full"] }
bytes = "1.4.0"
async-trait = "0.1.68"
sled = "0.34.7"
byte-unit = "4.0.19"
humantime = "2.1.0"
futures = "0.3.28"
