name: Sanity
on:
  workflow_call:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: clechasseur/rs-cargo@v2
        with:
          command: check
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - uses: clechasseur/rs-cargo@v2
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: clechasseur/rs-cargo@v2
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

# Uncomment this when we have a proper release - 1.0.0
#   semver-checks:
#     name: SemVer SDK
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: obi1kenobi/cargo-semver-checks-action@v2
#         with:
#           package: iggy
